ALTER TABLE "audit_logs"
  DROP COLUMN IF EXISTS "userId",
  DROP COLUMN IF EXISTS "entity",
  DROP COLUMN IF EXISTS "entityId",
  DROP COLUMN IF EXISTS "metadata",
  DROP COLUMN IF EXISTS "ipAddress",
  DROP COLUMN IF EXISTS "userAgent",
  DROP COLUMN IF EXISTS "tenantId",
  ADD COLUMN IF NOT EXISTS "actorId"    TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "actorEmail" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "targetType" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "targetName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "detail"     TEXT;